title: Abigail Adegbiji
description: Personal website and writing
url: ""
baseurl: ""
markdown: kramdown
permalink: /articles/:title/

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post